const countryCodes = {
    "Albania": "al",
    "Algeria": "dz",
    "Andorra": "ad",
    "Angola": "ao",
    "Argentina": "ar",
    "Austria": "at",
    "Belgium": "be",
    "Brazil": "br",
    "Bulgaria": "bg",
    "Cameroon": "cm",
    "Canada": "ca",
    "Cape Verde": "cv",
    "Chile": "cl",
    "Colombia": "co",
    "Congo": "cd",
    "Costa Rica": "cr",
    "Croatia": "hr",
    "Czech Republic": "cz",
    "Denmark": "dk",
    "Dominican Republic": "do",
    "Ecuador": "ec",
    "England": "en",
    "Equatorial Guinea": "gq",
    "Estonia": "ee",
    "France": "fr",
    "Georgia": "ge",
    "Germany": "de",
    "Ghana": "gh",
    "Greece": "gr",
    "Guadeloupe": "gp",
    "Guinea": "gn",
    "Hungary": "hu",
    "Iceland": "is",
    "Ireland": "ie",
    "Italy": "it",
    "Ivory Coast": "ci",
    "Japan": "jp",
    "Macedonia": "mk",
    "Mali": "ml",
    "Mauritania": "mr",
    "Mexico": "mx",
    "Morocco": "ma",
    "Mozambique": "mz",
    "Netherlands": "nl",
    "Nigeria": "ng",
    "Norway": "no",
    "Paraguay": "py",
    "Peru": "pe",
    "Poland": "pl",
    "Portugal": "pt",
    "Romania": "ro",
    "Russia": "ru",
    "Scotland": "gb-sct",
    "Senegal": "sn",
    "Serbia": "rs",
    "Sierra Leone": "sl",
    "Slovakia": "sk",
    "Slovenia": "si",
    "South Korea": "kr",
    "Spain": "es",
    "Suriname": "sr",
    "Sweden": "se",
    "Switzerland": "ch",
    "Togo": "tg",
    "Turkey": "tr",
    "Ukraine": "ua",
    "United States": "us",
    "Uruguay": "uy",
    "Venezuela": "ve"
}

export function getCountryCode(country) {
    return countryCodes[country];
}