### GET main page
GET http://localhost:1234/

### GET all teams
GET http://localhost:1234/teams

### GET all teams founded in 1898
GET http://localhost:1234/teams?year=1898

### GET all teams from Barcelona
GET http://localhost:1234/teams?city=barcelona

### GET alaves
GET http://localhost:1234/teams/5

### GET athletic club players
GET http://localhost:1234/teams/1/players

### GET all players
GET http://localhost:1234/players

### GET Nico Williams
GET http://localhost:1234/players/23

### POST new match

POST http://localhost:1234/teams
Content-Type: application/json

{
    "name": "CE Hospitalet",
    "year": 1957,
    "website": "https://www.celh.cat/",
    "president": "Jordi Garcia",
    "badge": "https://upload.wikimedia.org/wikipedia/en/4/4b/CE_L%27Hospitalet.png",
    "city": "Hospitalet de Llobregat",
    "mainColor": "#FF0000",
    "secondaryColor": "#FFFFFF"
}

### UPDATE team
PATCH http://localhost:1234/teams/21
Content-Type: application/json

{
    "name": "CE Hospitalleeet",
    "year": 1965,
    "secondaryColor": "#000000"
}

### DELETE team
DELETE http://localhost:1234/teams/21


### POST new player
POST http://localhost:1234/players
Content-Type: application/json

{
    "name": "Oriol",
    "lastName": "Romeu",
    "knownAs": "Oriol Romeu",
    "number": 14,
    "height": 183,
    "country": "Spain",
    "position": "Midfielder",
    "birthday": "1991-09-24",
    "photo": "https://statics-maker.llt-services.com/gir/images/2024/08/14/original/30a5680b-f84e-4665-8f66-2007beb8f725-563.png",
    "team": 8
}