### GET main page
GET http://localhost:1234/

### POST new match

POST http://localhost:1234/match
Content-Type: application/json

{
    "league": "LaLiga EA Sports",
    "matchday": 10,
    "date": "2024-12-20 21:00:00",
    "local_team": "Betis",
    "away_team": "Valencia",
    "stadium": "Benito Villamarín"

}