### GET main page
GET http://localhost:1234/

### GET all teams
GET http://localhost:1234/teams

### GET all teams founded in 1898
GET http://localhost:1234/teams?year=1898

### GET all teams from Barcelona
GET http://localhost:1234/teams?city=barcelona

### GET alaves
GET http://localhost:1234/teams/5

### GET athletic club players
GET http://localhost:1234/teams/1/players

### GET fcbarcelona matches
GET http://localhost:1234/teams/6/matches

### GET all players
GET http://localhost:1234/players

### GET Nico Williams
GET http://localhost:1234/players/23

### POST new match

POST http://localhost:1234/teams
Content-Type: application/json

{
    "name": "CE Hospitalet",
    "year": 1957,
    "website": "https://www.celh.cat/",
    "president": "Jordi Garcia",
    "badge": "https://upload.wikimedia.org/wikipedia/en/4/4b/CE_L%27Hospitalet.png",
    "city": "Hospitalet de Llobregat",
    "mainColor": "#FF0000",
    "secondaryColor": "#FFFFFF"
}

### UPDATE team
PATCH http://localhost:1234/teams/21
Content-Type: application/json

{
    "name": "CE Hospitalleeet",
    "year": 1965,
    "secondaryColor": "#000000"
}

### DELETE team
DELETE http://localhost:1234/teams/21


### POST new player
POST http://localhost:1234/players
Content-Type: application/json

{
    "name": "Pau",
    "lastName": "Cabanes de la Torre",
    "knownAs": "Cabanes",
    "number": 33,
    "height": 179,
    "country": "Spain",
    "position": "Forward",
    "birthday": "2005-02-17",
    "photo": "https://villarrealcf.es/wp-content/uploads/2021/09/18-Cabanes.png",
    "team": 20
}

### GET matches
GET http://localhost:1234/matches?matchday=12

### GET match
GET http://localhost:1234/matches/2024-08-18 21:30:00,12,14,12,1

### POST new match
POST http://localhost:1234/matches
Content-Type: application/json

{
    "matchdate": "2025-01-03",
    "localTeam": "valencia",
    "awayTeam": "real madrid",
    "stadium": 10,
    "matchday": 12
}

### GET leagues
GET http://localhost:1234/leagues

### GET league
GET http://localhost:1234/leagues/1

### GET league table
GET http://localhost:1234/leagues/1/table

### GET TeamMatchStats
GET http://localhost:1234/teammatchstats/

### POST TeamMatchStats
POST http://localhost:1234/teammatchstats
Content-Type: application/json

{
    "team": "real madrid",
    "matchdate": "2024-08-29 21:30:00",
    "possession": 56,
    "shots": 25,
    "shotsOnTarget": 8,
    "corners": 6,
    "offsides": 0,
    "fouls": 13,
    "goals": 1
}